version: '3'
services:
  weather-alerting-backend:
    build: ../
    container_name: weather-alerting-backend
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    depends_on:
      - "mongodb"
    restart: always
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=test
     - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
     - weather-alerting-dbdata:/data/db
volumes:
  weather-alerting-dbdata:
    driver: local